Création d'adresses
etalab/contribution-adresse pull request #14
Opened 2017-05-19 15:22 UTC by tmerlier

Possibilité d'ajouté (temporairement) des adresses.
Il est également possible de supprimer ou modifier les adresses crées.

**ATTENTION**: `address.town` est pour le moment une valeur en dure.
<img width="296" alt="capture d ecran 2017-05-19 a 17 21 51" src="https://cloud.githubusercontent.com/assets/7040549/26254697/bdf1fe10-3cb7-11e7-9a05-a5a22a540a40.png">
<img width="296" alt="capture d ecran 2017-05-19 a 17 22 12" src="https://cloud.githubusercontent.com/assets/7040549/26254700/bf4a0050-3cb7-11e7-90a6-ef6304439b03.png">

2017-05-19 20:55 UTC, jdesboeufs requested changes
Elle est pas buggée l'image ?

2017-05-19 20:55 UTC, jdesboeufs commented on front/public/index.html
> +<script src="/dist/CreateAddress.js"></script>
CreateAddress
AddAddress 
Il faudrait choisir :)

2017-05-19 20:55 UTC, jdesboeufs commented on front/public/style.css
> +.Menu {
Devrait plutôt être en minuscule

2017-05-19 20:55 UTC, jdesboeufs commented on front/public/style.css
> +.Address {
Idem

2017-05-19 20:55 UTC, jdesboeufs commented on front/src/Address.js
> +    const { address, editAddress } = this.props
editAddress et removeAddress sont un peu ambigus dans ce composant.
`onEdit`, `onChange`, `onDelete` me paraissent plus standards.
Par contre à l'étage du dessus tu peux laisser ces noms.

2017-05-19 20:55 UTC, jdesboeufs commented on front/src/Address.js
> +    let address = {town: e.target.value, street: newAddress.street}
const

2017-05-19 20:55 UTC, jdesboeufs commented on front/src/Address.js
> +    let address = {town: newAddress.town, street: e.target.value}
const

2017-05-19 20:55 UTC, jdesboeufs commented on front/src/Address.js
> +  editing() {
edit

2017-05-19 20:55 UTC, jdesboeufs commented on front/src/app.js
> +        markersCopy.splice(markersCopy[i], 1)
Popopo 💃

2017-05-19 20:55 UTC, jdesboeufs commented on front/src/app.js
> +        <LeafletMap displayAddress={this.displayAddress} coords={coords} markers={markers} fullscreen={fullscreen} closeForm={this.closeForm} />
Suggestion :
```
onShowAddress={this.displayAddress} onCloseForm={this.closeForm}
```

2017-05-22 06:28 UTC, tmerlier commented on front/public/style.css
> +.Menu {
J'ai préféré laisser la majuscule car il s'agit ici d'un `component`

2017-05-22 06:37 UTC, tmerlier commented on front/public/index.html
> +<script src="/dist/CreateAddress.js"></script>
`CreateAddress` est le composant servant à la création/édition d'une adresse. C'est un formulaire. Alors que `AddAddres` et `AddAddressButton` servent à l'ajout, de le sens de sauvegarde, d'adresse en mémoire.

2017-05-22 06:38 UTC, tmerlier commented on front/src/Address.js
> +  editing() {
`edit` est déjà le nom d'une autre méthode.

2017-05-22 07:33 UTC, tmerlier commented
De quelle image tu parles ?

2017-05-22 13:08 UTC, jdesboeufs approved these changes

2017-05-22 13:45 UTC, merged