Page d'accueil pour la première visite
etalab/contribution-adresse pull request #23
Opened 2017-05-31 15:12 UTC by tmerlier

<img width="284" alt="capture d ecran 2017-05-31 a 17 10 11" src="https://cloud.githubusercontent.com/assets/7040549/26639042/0b1c79ca-4624-11e7-81c0-4c7acbe0dcf0.png">

Un premier jet de ce que pourrait donner une page d'accueil. Il faut rajouter quelques lignes pour expliquer la principe à l'utilisateur et voir le wording... des suggestions ?

2017-05-31 15:13 UTC, tmerlier commented
Attention cette PR a pour base la [PR22](https://github.com/etalab/contribution-adresse/pull/22)

2017-06-01 08:51 UTC, jdesboeufs requested changes
Et pourquoi pas avec un SVG, mais ça peut faire l'objet d'une PR ultérieure.

2017-06-01 08:51 UTC, jdesboeufs commented on front/src/Welcome.js
> +          <div><h1>C<img class="logo" src="addHome.svg"/>ntrib'Adresses</h1></div>
Il manque un `alt="o"` pour les liseuses.

2017-06-02 08:49 UTC, jdesboeufs requested changes

2017-06-02 08:49 UTC, jdesboeufs commented on front/src/app.js
> +    console.log(user);
😬

2017-06-02 09:09 UTC, jdesboeufs submitted a review, later dismissed

2017-06-02 09:11 UTC, jdesboeufs approved these changes

2017-06-02 09:23 UTC, merged