Tutoriel
etalab/contribution-adresse pull request #25
Opened 2017-06-05 09:22 UTC by tmerlier

Ajout d'un tutoriel afin de mieux accueillir l'utilisateur et lui faire comprendre la démarche qui se cache derrière cet outil.

<img width="197" alt="capture d ecran 2017-06-05 a 11 20 11" src="https://cloud.githubusercontent.com/assets/7040549/26778303/f85a252e-49e0-11e7-89ed-075aecad0f2d.png">

Le wording est à revoir ;) À l'écoute de toutes vos propositions !

2017-06-05 09:22 UTC, tmerlier commented
Je me sers actuellement de cette branche comme base pour une nouvelle PR amenant les badges récompense.

2017-06-06 13:15 UTC, jdesboeufs requested changes

2017-06-06 13:15 UTC, jdesboeufs commented on front/src/AddAddressButton.js
> +    const { openMenu, tutoNextStep } = this.props
Pourquoi ne pas passer une fonction `onClick` prête à l'emploi ?

2017-06-06 13:15 UTC, jdesboeufs commented on front/src/CreateAddress.js
> +    const { coords, createAddress, tutoNextStep } = this.props
Pareil

2017-06-06 13:15 UTC, jdesboeufs commented on front/src/Dashboard.js
> +        <AddAddressButton openMenu={openMenu} tutoNextStep={tutoNextStep} />
Pareil

2017-06-06 13:15 UTC, jdesboeufs commented on front/src/Menu.js
> +    const { selectedAddress, coords, createAddress, editAddress, removeAddress, tutoNextStep } = this.props
Pareil

2017-06-06 13:20 UTC, tmerlier commented
`tutoNextStep` à besoin de l'index de prochain bloc "tuto" à afficher. Un simple `+1` est à éviter car si l'utilisateur ne suis pas le tutorial, celui-ci ne doit pas perdre le fil.

2017-06-09 13:20 UTC, jdesboeufs approved these changes

2017-06-09 13:20 UTC, merged