Meilleur gestion des pop-ups
etalab/contribution-adresse pull request #39
Opened 2017-06-22 13:46 UTC by tmerlier

Réduction de code pour `PopUpManager` et désormais toutes les étapes du tutorat se trouve dans `Tuto`.

<img width="210" alt="capture d ecran 2017-06-22 a 15 38 28" src="https://user-images.githubusercontent.com/7040549/27437079-7a0a6970-5761-11e7-8d87-cddc49eec439.png">

2017-07-03 18:46 UTC, jdesboeufs requested changes
Review partielle

2017-07-03 18:46 UTC, jdesboeufs commented on front/src/PopUpManager.js
>  import Tuto from './Tuto'
Il ne devrait pas y avoir de référence à `Tuto` dans ce composant.

2017-07-03 18:46 UTC, jdesboeufs commented on front/src/PopUpManager.js
> +const PopUpManager = ({ userEmail, newBadge, tuto, setEmail, tutoNextStep, resetNewBadge }) => {
Trop spécifique, ou alors il faut renommer le composant.

2017-07-04 07:43 UTC, tmerlier commented on front/src/PopUpManager.js
> +const PopUpManager = ({ userEmail, newBadge, tuto, setEmail, tutoNextStep, resetNewBadge }) => {
Que penses-tu de simplement l'appeler `PopUps` ?

2017-07-04 09:32 UTC, tmerlier commented
cc @jdesboeufs

2017-07-04 09:37 UTC, jdesboeufs approved these changes

2017-07-04 09:39 UTC, merged